//
//  PreviewRouter.swift
//  NesineCaseApp
//
//  Created by Anıl Taha Uyar on 12.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PreviewRoutingLogic : AnyObject {
    
}

protocol PreviewDataPassing {
    var dataStore: PreviewDataStore? { get }
}

class PreviewRouter: NSObject, PreviewRoutingLogic, PreviewDataPassing {
    weak var viewController: PreviewViewController?
    var dataStore: PreviewDataStore?
    
    
}
