//
//  SearchViewControllerTests.swift
//  NesineCaseApp
//
//  Created by Anıl Taha Uyar on 13.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import NesineCaseApp
import XCTest

class SearchViewControllerTests: XCTestCase {
    
    var sut: SearchViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupSearchViewController()
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSearchViewController() {
        sut = SearchViewController()
    }
    
    
    class SearchBusinessLogicSpy: SearchBusinessLogic {
        var getSoftwareCalled = false
        
        func getSoftware(with searchText: String) {
            getSoftwareCalled = true
        }
        
    }
    
    // MARK: Tests
    
    func testGetSoftware() {
        let spy = SearchBusinessLogicSpy()
        let searchController = UISearchController()
        searchController.searchBar.text = "asdd"
        sut.interactor = spy
        sut.viewDidLoad()
        sut.searchBarTextDidEndEditing(searchController.searchBar)
        
        XCTAssertTrue(spy.getSoftwareCalled)
        
    }
    
    func testGetSoftwareWith2Char() {
        let spy = SearchBusinessLogicSpy()
        let searchController = UISearchController()
        searchController.searchBar.text = "as"
        sut.interactor = spy
        sut.viewDidLoad()
        sut.searchBarTextDidEndEditing(searchController.searchBar)
        XCTAssertFalse(spy.getSoftwareCalled)
    }
    
    func testDisplaySearchList() {
        let defaultImage = UIImage.init(named: "Default")!
        var updatedItem: [String: Any] = [:]
        updatedItem["image"] = defaultImage
        updatedItem["type"] = "small"
        sut.receiveData(NSNotification.init(name: NSNotification.Name(rawValue: "complatedImage"), object: nil, userInfo: updatedItem))

    }
    
}
