//
//  SearchRouter.swift
//  NesineCaseApp
//
//  Created by Anıl Taha Uyar on 9.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchRoutingLogic : AnyObject
{
    func routeToPreviewPage(with image: UIImage)
    
}

protocol SearchDataPassing
{
  var dataStore: SearchDataStore? { get }
}

class SearchRouter: NSObject, SearchRoutingLogic, SearchDataPassing
{
  weak var viewController: SearchViewController?
  var dataStore: SearchDataStore?
  
  // MARK: Routing
  
    func routeToPreviewPage(with image: UIImage) {
        let destinationVC = PreviewViewController()
        var destinationDS = destinationVC.router!.dataStore!
        passModelToPreview(image: image, destination: &destinationDS)
        navigateToPreview(source: viewController!, destination: destinationVC)
    }

  // MARK: Navigation
  
    func navigateToPreview(source: SearchViewController, destination: PreviewViewController){
        source.show(destination, sender: nil)
    }
  
  
  // MARK: Passing data
  
    func passModelToPreview(image: UIImage, destination: inout PreviewDataStore) {
        destination.image = image
        //aslında değişmiyor ama inout yolladım
    }
}
