//
//  SearchPresenter.swift
//  NesineCaseApp
//
//  Created by Anıl Taha Uyar on 9.04.2022.
//  Copyright (c) 2022 AntaApp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


protocol SearchPresentationLogic: AnyObject {
    func presentSoftware(response: SearchModel.Response)
    func presentSoftware(with imageModel: SearchModel.ImageModel)
}

final class SearchPresenter: SearchPresentationLogic {
    weak var viewController: SearchDisplayLogic?
    
    func presentSoftware(response: SearchModel.Response) {
        
        var listViewModel:[SearchModel.ResultModel] = []
        
        if let results = response.results {
            results.forEach{ responseModel in
                let resultModel = SearchModel.ResultModel.init(screenshotUrls: responseModel.screenshotUrls)
                listViewModel.append(resultModel)
            }
        }
        viewController?.displaySearchList(listViewModel: listViewModel)
    }
    
    func presentSoftware(with imageModel: SearchModel.ImageModel) {
        viewController?.displaySearchList(imageListModel: imageModel)
    }
    
}
