//
//  PreviewPresenterTests.swift
//  NesineCaseApp
//
//  Created by Anıl Taha Uyar on 13.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import NesineCaseApp
import XCTest

class PreviewPresenterTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: PreviewPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupPreviewPresenter()
  }
  
  // MARK: Test setup
  
  func setupPreviewPresenter() {
    sut = PreviewPresenter()
  }
  
  // MARK: Test doubles
  
  class PreviewDisplayLogicSpy: PreviewDisplayLogic {
      var displayImageCalled = false
      
      func displayImage(image: UIImage) {
          displayImageCalled = true
      }
  }
  
  // MARK: Tests
    func testDisplayImage() {
        let spy = PreviewDisplayLogicSpy()
        sut.viewController = spy
        let mockImage = UIImage(named: "Default")!
        sut.presentImage(image: mockImage)
        XCTAssertTrue(spy.displayImageCalled)

    }

}
